### ISSUE TITLE
Remove all of the instances of print

### ISSUE THREAD

**Issue by dashwav** [dashwav/nano-chan#44]
Print isn't how we should be logging errors and such, ideally we should be replacing all of the `print` statements with `logger` (`self.logger`) statements

**Comment by GilSandler** [comment]
Hey,
I'm pretty new to open source contributions, but want to help :)
I can take over the issue, if no one is handling it yet

**Comment by dashwav** [comment]
@GilSandler Thanks for your interest in helping, I think the issue could have been worded a bit better - I was hoping to replace the print statements with the logger that is preconfigured and set up in the bot instance here.

You can see an example usage [here](https://github.com/dashwav/nano-chan/blob/master/cogs/filter.py#L48). Ideally if it is a simple statement INFO is correct, but if it is in a catch block it should probably be WARNING.

Let me know if you have any questions

**Comment by GilSandler** [comment]
@dashwav I changed everything according to your instruction, hope I got it right this time :)
I did however have to leave one print unchanged (in db_utils) since it's out of scope.
