### ISSUE TITLE
Add dedicated and limited to roles to remove

### ISSUE THREAD

**Issue by dashwav** [dashwav/nano-chan#7]
https://github.com/dashwav/nano-chan/blob/master/cogs/janitor.py#L74

Just need to add dedicated/limited here - might also change format to 
```
Roles = [
    artsy,
    etc,
   ...
]
```

**Comment by niealeh** [comment]
Limited is meant for users who only join voice, or only use the server for gaming channels. It is meant to not be removed on a reset.

**Comment by dashwav** [comment]
Fixed in #8
